/**
 * Reads the harness's real implementation files off disk and emits them as a
 * TypeScript map, so a route can render the exact code that runs rather than a
 * re-typed approximation.
 *
 * Angular's esbuild pipeline has no `?raw` import, so this runs as a prestart /
 * prebuild step instead. Regenerate with `npm run gen:sources`.
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, posix, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));

/** Files and directories whose contents routes are allowed to display. */
const TARGETS = [
  'server.ts',
  'src/styles.css',
  'src/app/app.config.ts',
  'src/app/features',
];

const EXTENSIONS = ['.ts', '.html', '.css'];

function walk(absolute: string, out: string[]): void {
  if (!statSync(absolute).isDirectory()) {
    out.push(absolute);
    return;
  }
  for (const entry of readdirSync(absolute).sort()) {
    const child = join(absolute, entry);
    if (statSync(child).isDirectory()) {
      walk(child, out);
    } else if (EXTENSIONS.some((ext) => entry.endsWith(ext))) {
      out.push(child);
    }
  }
}

const files: string[] = [];
for (const target of TARGETS) {
  walk(join(root, target), files);
}

const entries = files
  .map((absolute) => {
    const key = relative(root, absolute).split(sep).join(posix.sep);
    const body = readFileSync(absolute, 'utf8');
    return `  ${JSON.stringify(key)}: ${JSON.stringify(body)},`;
  })
  .join('\n');

const output = `/**
 * GENERATED by scripts/generate-sources.ts — do not edit.
 *
 * Maps a repo-relative path to that file's exact contents at build time, so
 * what a route displays is byte-identical to what runs.
 */
export const SOURCES: Record<string, string> = {
${entries}
};

export function readSource(path: string): string {
  return SOURCES[path] ?? \`// Source not generated for \${path}. Run: npm run gen:sources\`;
}
`;

writeFileSync(join(root, 'src/app/lib/generated-sources.ts'), output, 'utf8');
console.log(`Generated ${files.length} source entries.`);
